package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import control.myawt.SKPoint2D;
import control.util.Ultility;
import java.awt.Component;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.text.JTextComponent;
import model.tuple.MyPair;

public class Rotation2DInput extends javax.swing.JDialog implements ActionListener {

    public static final MyPair DEGREE_ANGLE_BOUND = new MyPair(0, 360);
    
    /**
     * Input center-point.
     */
    private SKPoint2D acceptCenterPoint = new SKPoint2D();

    /**
     * Creates new form Rotation2DInput
     */
    public Rotation2DInput(java.awt.Frame parent) {
        super(parent, true);
        initComponents();

        setModalityType(ModalityType.APPLICATION_MODAL);
        setLocationRelativeTo(parent);
        setTitle("Rotation Transform Input");
        setResizable(false);

        customComponents();
    }

    private void customComponents() {
        btnGroupRotateMode.add(rbtCCW);
        btnGroupRotateMode.add(rbtCW);

        btnGroupRotateMode.setSelected(rbtCCW.getModel(), true);

        btnCancel.setRequestFocusEnabled(false);

        btnCancel.addActionListener(this);
        btnOK.addActionListener(this);

        textfCenterPointCoordX.setName("Input center point coordinate x");
        textfCenterPointCoordY.setName("Input center point coordinate y");
        textfAngle.setName("Input angle");

        for (Component comp : pnInner.getComponents()) {
            if (comp instanceof JTextComponent) {
                comp.addFocusListener(new FocusAdapter() {
                    @Override
                    public void focusGained(FocusEvent e) {
                        ((JTextComponent) comp).setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
                    }
                });
            }
        }
    }

    @Override
    public void actionPerformed(ActionEvent event) {
        Object source = event.getSource();

        if (source == btnOK) {
            acceptCenterPoint.convertToSystemCoord();
            if (!process()) {
                return;
            }
            dispose();
        } else if (source == btnCancel) {
            dispose();
        }
    }

    private boolean process() {
        try {
            MyPair xBound = ((MainFrame) getParent()).getDrawingPanel()
                    .getXBound();

            acceptCenterPoint.setCoordX(Ultility.getValidInputComponent(
                    textfCenterPointCoordX, false, xBound));

            MyPair yBound = ((MainFrame) getParent()).getDrawingPanel()
                    .getYBound();

            acceptCenterPoint.setCoordY(Ultility.getValidInputComponent(
                    textfCenterPointCoordY, false, yBound));

            double angle = Math.toRadians(Ultility.getValidInputComponent(
                    textfAngle, false, DEGREE_ANGLE_BOUND));

            if (rbtCW.isSelected()) {
                angle = -angle;
            }

            ((MainFrame) getParent()).getDrawingPanel().paintRotation(
                    acceptCenterPoint, angle);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupRotateMode = new javax.swing.ButtonGroup();
        pnInner = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textfAngle = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        textfCenterPointCoordX = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rbtCCW = new javax.swing.JRadioButton();
        rbtCW = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        labelCenterpointRotationINput = new javax.swing.JLabel();
        textfCenterPointCoordY = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Angle (degree value 0..360):");

        jLabel1.setText("°");

        btnOK.setText("OK");

        jLabel2.setText("X:");

        rbtCCW.setText("counterclockwise");

        rbtCW.setText("clockwise");

        jLabel3.setText("Y:");

        labelCenterpointRotationINput.setText("Center point coordinate:");

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout pnInnerLayout = new javax.swing.GroupLayout(pnInner);
        pnInner.setLayout(pnInnerLayout);
        pnInnerLayout.setHorizontalGroup(
            pnInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInnerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnInnerLayout.createSequentialGroup()
                        .addComponent(rbtCCW)
                        .addGap(49, 49, 49)
                        .addComponent(rbtCW))
                    .addGroup(pnInnerLayout.createSequentialGroup()
                        .addGroup(pnInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnInnerLayout.createSequentialGroup()
                                .addComponent(labelCenterpointRotationINput)
                                .addGap(27, 27, 27)
                                .addGroup(pnInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInnerLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(textfCenterPointCoordX, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInnerLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(textfCenterPointCoordY, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnInnerLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textfAngle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInnerLayout.createSequentialGroup()
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnInnerLayout.setVerticalGroup(
            pnInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInnerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnInnerLayout.createSequentialGroup()
                        .addGroup(pnInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textfCenterPointCoordX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textfCenterPointCoordY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelCenterpointRotationINput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textfAngle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(pnInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtCW)
                    .addComponent(rbtCCW))
                .addGap(18, 18, 18)
                .addGroup(pnInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnInner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnInner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rotation2DInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Rotation2DInput dialog = new Rotation2DInput(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.ButtonGroup btnGroupRotateMode;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelCenterpointRotationINput;
    private javax.swing.JPanel pnInner;
    private javax.swing.JRadioButton rbtCCW;
    private javax.swing.JRadioButton rbtCW;
    private javax.swing.JTextField textfAngle;
    private javax.swing.JTextField textfCenterPointCoordX;
    private javax.swing.JTextField textfCenterPointCoordY;
    // End of variables declaration//GEN-END:variables
}
