/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author DELL
 */
public class Symmetry2DInput extends javax.swing.JDialog {

    /**
     * Creates new form Symmetry2DInput
     */
    public Symmetry2DInput(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        setTitle("Symmetry Transform Input");
        if (modal) {
            this.setModalityType(ModalityType.APPLICATION_MODAL);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelChooseObjectSymmetry = new javax.swing.JLabel();
        combObjectSymmetry = new javax.swing.JComboBox<>();
        panelInner = new javax.swing.JPanel();
        innerPanelPointSymmetryInput = new javax.swing.JPanel();
        labelPointSymmetryInputCoordX = new javax.swing.JLabel();
        labelPointSymmetryInputCoordY = new javax.swing.JLabel();
        textfPointSymmetryInputCoordX = new javax.swing.JTextField();
        textfPointSymmetryInputCoordY = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        innerPanelLineSymmetryInput = new javax.swing.JPanel();
        labelLineSymmetryInputCoeffA = new javax.swing.JLabel();
        textfLineSymmetryInputCoeffA = new javax.swing.JTextField();
        labelLineSymmetryInputCoeffB = new javax.swing.JLabel();
        textfLineSymmetryInputCoeffB = new javax.swing.JTextField();
        labelLineSymmetryInputCoeffC = new javax.swing.JLabel();
        textfLineSymmetryInputCoeffC = new javax.swing.JTextField();
        labelSymmetryInput = new javax.swing.JLabel();
        btnSymmetryOK = new javax.swing.JButton();
        btnSymmetryCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelChooseObjectSymmetry.setText("Choose object:");

        combObjectSymmetry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O(0, 0)", "Ox", "Oy", "Point", "Line" }));

        panelInner.setLayout(new java.awt.CardLayout());

        labelPointSymmetryInputCoordX.setText("X coordinate:");

        labelPointSymmetryInputCoordY.setText("Y coordinate:");

        jLabel1.setText("Center-point:");

        javax.swing.GroupLayout innerPanelPointSymmetryInputLayout = new javax.swing.GroupLayout(innerPanelPointSymmetryInput);
        innerPanelPointSymmetryInput.setLayout(innerPanelPointSymmetryInputLayout);
        innerPanelPointSymmetryInputLayout.setHorizontalGroup(
            innerPanelPointSymmetryInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerPanelPointSymmetryInputLayout.createSequentialGroup()
                .addGroup(innerPanelPointSymmetryInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(innerPanelPointSymmetryInputLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(innerPanelPointSymmetryInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelPointSymmetryInputCoordX)
                            .addComponent(labelPointSymmetryInputCoordY))
                        .addGap(38, 38, 38)
                        .addGroup(innerPanelPointSymmetryInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textfPointSymmetryInputCoordY, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfPointSymmetryInputCoordX, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(innerPanelPointSymmetryInputLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        innerPanelPointSymmetryInputLayout.setVerticalGroup(
            innerPanelPointSymmetryInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerPanelPointSymmetryInputLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(innerPanelPointSymmetryInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPointSymmetryInputCoordX)
                    .addComponent(textfPointSymmetryInputCoordX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(innerPanelPointSymmetryInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPointSymmetryInputCoordY)
                    .addComponent(textfPointSymmetryInputCoordY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        panelInner.add(innerPanelPointSymmetryInput, "card2");

        innerPanelLineSymmetryInput.setPreferredSize(new java.awt.Dimension(441, 177));

        labelLineSymmetryInputCoeffA.setText("A coefficient:");

        labelLineSymmetryInputCoeffB.setText("B coefficient:");

        labelLineSymmetryInputCoeffC.setText("C coefficient:");

        labelSymmetryInput.setText("Line Ax + By = C:");

        javax.swing.GroupLayout innerPanelLineSymmetryInputLayout = new javax.swing.GroupLayout(innerPanelLineSymmetryInput);
        innerPanelLineSymmetryInput.setLayout(innerPanelLineSymmetryInputLayout);
        innerPanelLineSymmetryInputLayout.setHorizontalGroup(
            innerPanelLineSymmetryInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerPanelLineSymmetryInputLayout.createSequentialGroup()
                .addGroup(innerPanelLineSymmetryInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(innerPanelLineSymmetryInputLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(innerPanelLineSymmetryInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(innerPanelLineSymmetryInputLayout.createSequentialGroup()
                                .addComponent(labelLineSymmetryInputCoeffA)
                                .addGap(35, 35, 35)
                                .addComponent(textfLineSymmetryInputCoeffA, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, innerPanelLineSymmetryInputLayout.createSequentialGroup()
                                .addComponent(labelLineSymmetryInputCoeffB)
                                .addGap(35, 35, 35)
                                .addComponent(textfLineSymmetryInputCoeffB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(innerPanelLineSymmetryInputLayout.createSequentialGroup()
                                .addComponent(labelLineSymmetryInputCoeffC)
                                .addGap(35, 35, 35)
                                .addComponent(textfLineSymmetryInputCoeffC, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(innerPanelLineSymmetryInputLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelSymmetryInput)))
                .addGap(149, 149, 149))
        );
        innerPanelLineSymmetryInputLayout.setVerticalGroup(
            innerPanelLineSymmetryInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerPanelLineSymmetryInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSymmetryInput)
                .addGap(18, 18, 18)
                .addGroup(innerPanelLineSymmetryInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLineSymmetryInputCoeffA)
                    .addComponent(textfLineSymmetryInputCoeffA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(innerPanelLineSymmetryInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLineSymmetryInputCoeffB)
                    .addComponent(textfLineSymmetryInputCoeffB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(innerPanelLineSymmetryInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLineSymmetryInputCoeffC)
                    .addComponent(textfLineSymmetryInputCoeffC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelInner.add(innerPanelLineSymmetryInput, "card3");

        btnSymmetryOK.setText("Ok");

        btnSymmetryCancel.setText("Cancel");
        btnSymmetryCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSymmetryCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelChooseObjectSymmetry)
                .addGap(29, 29, 29)
                .addComponent(combObjectSymmetry, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelInner, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSymmetryOK, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnSymmetryCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelChooseObjectSymmetry)
                    .addComponent(combObjectSymmetry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInner, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSymmetryOK)
                    .addComponent(btnSymmetryCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSymmetryCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSymmetryCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSymmetryCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Symmetry2DInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Symmetry2DInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Symmetry2DInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Symmetry2DInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Symmetry2DInput dialog = new Symmetry2DInput(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSymmetryCancel;
    private javax.swing.JButton btnSymmetryOK;
    private javax.swing.JComboBox<String> combObjectSymmetry;
    private javax.swing.JPanel innerPanelLineSymmetryInput;
    private javax.swing.JPanel innerPanelPointSymmetryInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelChooseObjectSymmetry;
    private javax.swing.JLabel labelLineSymmetryInputCoeffA;
    private javax.swing.JLabel labelLineSymmetryInputCoeffB;
    private javax.swing.JLabel labelLineSymmetryInputCoeffC;
    private javax.swing.JLabel labelPointSymmetryInputCoordX;
    private javax.swing.JLabel labelPointSymmetryInputCoordY;
    private javax.swing.JLabel labelSymmetryInput;
    private javax.swing.JPanel panelInner;
    private javax.swing.JTextField textfLineSymmetryInputCoeffA;
    private javax.swing.JTextField textfLineSymmetryInputCoeffB;
    private javax.swing.JTextField textfLineSymmetryInputCoeffC;
    private javax.swing.JTextField textfPointSymmetryInputCoordX;
    private javax.swing.JTextField textfPointSymmetryInputCoordY;
    // End of variables declaration//GEN-END:variables
}
