package main;

import javax.swing.ImageIcon;
import javax.swing.UIManager;

public class Paint extends javax.swing.JFrame {

    /**
     * Creates new form PaintUI
     */
    private int size = 5;
    private int space = 2;
    private int width = 918;
    private int height = 718;

    public Paint() {
        initComponents();
        // this.getContentPane().setBackground(new java.awt.Color(248, 248, 248));

        // Set icon for this frame.
        ImageIcon img = new ImageIcon(getClass().getResource("/img/paintIcon.png"));
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DrawingArea = new DrawingArea(width,height,space,size);
        jLabel2 = new javax.swing.JLabel();
        Label_XCoord = new javax.swing.JLabel();
        Label_YCoord = new javax.swing.JLabel();
        ControlArea3 = new javax.swing.JPanel();
        Panel_Control_3 = new javax.swing.JPanel();
        Panel_Operation2 = new javax.swing.JPanel();
        Button_Undo3 = new javax.swing.JButton();
        Button_Redo3 = new javax.swing.JButton();
        Button_Save3 = new javax.swing.JButton();
        Button_OpenFile3 = new javax.swing.JButton();
        Label_Control_1 = new javax.swing.JLabel();
        Panel_Control_4 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        Panel_Shapes1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        Label_Control_3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ComboBox_LineMode = new javax.swing.JComboBox<>();
        ComboBox_LineDepth = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Panel_Control_5 = new javax.swing.JPanel();
        Panel_Tools = new javax.swing.JPanel();
        Button_ColorChooser1 = new javax.swing.JButton();
        Button_FillColor1 = new javax.swing.JButton();
        Button_ClearAll1 = new javax.swing.JButton();
        Button_Eraser1 = new javax.swing.JButton();
        Button_Select1 = new javax.swing.JButton();
        Button_Animation1 = new javax.swing.JButton();
        Button_Animation2 = new javax.swing.JButton();
        Button_Transform = new javax.swing.JButton();
        Label_Control_2 = new javax.swing.JLabel();
        Panel_View = new javax.swing.JPanel();
        Button_ColorChooser2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Label_Control_5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        Panel_Control_6 = new javax.swing.JPanel();
        Label_Control_4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(12, 240, 240));
        setResizable(false);

        DrawingArea.setBackground(new java.awt.Color(248, 248, 248));
        DrawingArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DrawingArea.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DrawingAreaMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout DrawingAreaLayout = new javax.swing.GroupLayout(DrawingArea);
        DrawingArea.setLayout(DrawingAreaLayout);
        DrawingAreaLayout.setHorizontalGroup(
            DrawingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DrawingAreaLayout.setVerticalGroup(
            DrawingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Coord.png"))); // NOI18N

        Label_XCoord.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_XCoord.setText("X:");

        Label_YCoord.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_YCoord.setText("Y:");

        Button_Undo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/undo.png"))); // NOI18N
        Button_Undo3.setToolTipText("Undo");

        Button_Redo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/redo.png"))); // NOI18N
        Button_Redo3.setToolTipText("Redo");

        Button_Save3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/saveFile.png"))); // NOI18N
        Button_Save3.setToolTipText("Save image");

        Button_OpenFile3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/openFile.png"))); // NOI18N
        Button_OpenFile3.setToolTipText("Open image");

        javax.swing.GroupLayout Panel_Operation2Layout = new javax.swing.GroupLayout(Panel_Operation2);
        Panel_Operation2.setLayout(Panel_Operation2Layout);
        Panel_Operation2Layout.setHorizontalGroup(
            Panel_Operation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Operation2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_Operation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Operation2Layout.createSequentialGroup()
                        .addComponent(Button_OpenFile3)
                        .addGap(7, 7, 7)
                        .addComponent(Button_Save3))
                    .addGroup(Panel_Operation2Layout.createSequentialGroup()
                        .addComponent(Button_Undo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Redo3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_Operation2Layout.setVerticalGroup(
            Panel_Operation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Operation2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_Operation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Save3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_OpenFile3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_Operation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Undo3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Redo3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        Label_Control_1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_Control_1.setForeground(new java.awt.Color(90, 90, 90));
        Label_Control_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Control_1.setText("File");
        Label_Control_1.setFocusable(false);
        Label_Control_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout Panel_Control_3Layout = new javax.swing.GroupLayout(Panel_Control_3);
        Panel_Control_3.setLayout(Panel_Control_3Layout);
        Panel_Control_3Layout.setHorizontalGroup(
            Panel_Control_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Control_3Layout.createSequentialGroup()
                .addGroup(Panel_Control_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_Operation2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_Control_3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Label_Control_1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        Panel_Control_3Layout.setVerticalGroup(
            Panel_Control_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Control_3Layout.createSequentialGroup()
                .addComponent(Panel_Operation2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_Control_1))
        );

        jScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Shape"));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/straightLine.png"))); // NOI18N
        jToggleButton1.setToolTipText("Straight line");
        jToggleButton1.setBorder(null);
        jToggleButton1.setContentAreaFilled(false);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/straightLine.png"))); // NOI18N
        jToggleButton2.setToolTipText("Straight line");
        jToggleButton2.setBorder(null);
        jToggleButton2.setContentAreaFilled(false);

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/straightLine.png"))); // NOI18N
        jToggleButton3.setToolTipText("Straight line");
        jToggleButton3.setBorder(null);
        jToggleButton3.setContentAreaFilled(false);

        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/straightLine.png"))); // NOI18N
        jToggleButton4.setToolTipText("Straight line");
        jToggleButton4.setBorder(null);
        jToggleButton4.setContentAreaFilled(false);

        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/straightLine.png"))); // NOI18N
        jToggleButton5.setToolTipText("Straight line");
        jToggleButton5.setBorder(null);
        jToggleButton5.setContentAreaFilled(false);

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/straightLine.png"))); // NOI18N
        jToggleButton6.setToolTipText("Straight line");
        jToggleButton6.setBorder(null);
        jToggleButton6.setContentAreaFilled(false);

        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/straightLine.png"))); // NOI18N
        jToggleButton7.setToolTipText("Straight line");
        jToggleButton7.setBorder(null);
        jToggleButton7.setContentAreaFilled(false);

        jToggleButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/straightLine.png"))); // NOI18N
        jToggleButton8.setToolTipText("Straight line");
        jToggleButton8.setBorder(null);
        jToggleButton8.setContentAreaFilled(false);

        jToggleButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/straightLine.png"))); // NOI18N
        jToggleButton9.setToolTipText("Straight line");
        jToggleButton9.setBorder(null);
        jToggleButton9.setContentAreaFilled(false);

        jToggleButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/straightLine.png"))); // NOI18N
        jToggleButton10.setToolTipText("Straight line");
        jToggleButton10.setBorder(null);
        jToggleButton10.setContentAreaFilled(false);

        javax.swing.GroupLayout Panel_Shapes1Layout = new javax.swing.GroupLayout(Panel_Shapes1);
        Panel_Shapes1.setLayout(Panel_Shapes1Layout);
        Panel_Shapes1Layout.setHorizontalGroup(
            Panel_Shapes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Shapes1Layout.createSequentialGroup()
                .addGroup(Panel_Shapes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_Shapes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_Shapes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_Shapes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_Shapes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        Panel_Shapes1Layout.setVerticalGroup(
            Panel_Shapes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Shapes1Layout.createSequentialGroup()
                .addGroup(Panel_Shapes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Shapes1Layout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_Shapes1Layout.createSequentialGroup()
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_Shapes1Layout.createSequentialGroup()
                        .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_Shapes1Layout.createSequentialGroup()
                        .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_Shapes1Layout.createSequentialGroup()
                        .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 494, Short.MAX_VALUE))
        );

        jScrollPane.setViewportView(Panel_Shapes1);

        Label_Control_3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_Control_3.setForeground(new java.awt.Color(90, 90, 90));
        Label_Control_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Control_3.setText("Shapes & Lines");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Format"));

        ComboBox_LineMode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ComboBox_LineMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ──────────────────", " ---------------------------------", " - ∙ - ∙ - ∙ - ∙ - ∙ - ∙ - ∙ - ∙ - ∙ - ∙ ", " ── ∙ ∙ ── ∙ ∙ ── ∙ ∙ ── ∙ ∙ ─" }));
        ComboBox_LineMode.setToolTipText("Line mode");

        ComboBox_LineDepth.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ComboBox_LineDepth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ──────────────────", " ---------------------------------", "- ∙ - ∙ - ∙ - ∙ - ∙ - ∙ - ∙ - ∙ - ∙ - ∙ -", "── ∙ ∙ ── ∙ ∙ ── ∙ ∙ ── ∙ ∙ ──" }));
        ComboBox_LineDepth.setToolTipText("Line mode");

        jLabel1.setText("Size:");

        jLabel3.setText("Style:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComboBox_LineMode, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComboBox_LineDepth, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_LineMode, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_LineDepth, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        javax.swing.GroupLayout Panel_Control_4Layout = new javax.swing.GroupLayout(Panel_Control_4);
        Panel_Control_4.setLayout(Panel_Control_4Layout);
        Panel_Control_4Layout.setHorizontalGroup(
            Panel_Control_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Control_4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_Control_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Control_4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Label_Control_3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_Control_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        Panel_Control_4Layout.setVerticalGroup(
            Panel_Control_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Control_4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_Control_3))
        );

        Button_ColorChooser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/colorpicker.png"))); // NOI18N
        Button_ColorChooser1.setToolTipText("Color picker");

        Button_FillColor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fillColor.png"))); // NOI18N
        Button_FillColor1.setToolTipText("Fill");

        Button_ClearAll1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clearAll.png"))); // NOI18N
        Button_ClearAll1.setToolTipText("Clear");

        Button_Eraser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eraser.png"))); // NOI18N
        Button_Eraser1.setToolTipText("Eraser");

        Button_Select1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/select.png"))); // NOI18N
        Button_Select1.setToolTipText("Select");

        Button_Animation1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/animations.png"))); // NOI18N
        Button_Animation1.setToolTipText("Animations");

        Button_Animation2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencil.png"))); // NOI18N
        Button_Animation2.setToolTipText("Animations");

        Button_Transform.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clearAll.png"))); // NOI18N
        Button_Transform.setToolTipText("Clear");

        javax.swing.GroupLayout Panel_ToolsLayout = new javax.swing.GroupLayout(Panel_Tools);
        Panel_Tools.setLayout(Panel_ToolsLayout);
        Panel_ToolsLayout.setHorizontalGroup(
            Panel_ToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ToolsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(Panel_ToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_ToolsLayout.createSequentialGroup()
                        .addComponent(Button_ColorChooser1)
                        .addGap(7, 7, 7)
                        .addComponent(Button_FillColor1)
                        .addGap(7, 7, 7)
                        .addComponent(Button_ClearAll1)
                        .addGap(7, 7, 7)
                        .addComponent(Button_Eraser1))
                    .addGroup(Panel_ToolsLayout.createSequentialGroup()
                        .addComponent(Button_Animation2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Select1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Animation1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Transform))))
        );
        Panel_ToolsLayout.setVerticalGroup(
            Panel_ToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ToolsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(Panel_ToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_ColorChooser1)
                    .addComponent(Button_FillColor1)
                    .addComponent(Button_ClearAll1)
                    .addComponent(Button_Eraser1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_ToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Transform)
                    .addComponent(Button_Animation1)
                    .addComponent(Button_Select1)
                    .addComponent(Button_Animation2))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        Label_Control_2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_Control_2.setForeground(new java.awt.Color(90, 90, 90));
        Label_Control_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Control_2.setText("Tools");

        javax.swing.GroupLayout Panel_Control_5Layout = new javax.swing.GroupLayout(Panel_Control_5);
        Panel_Control_5.setLayout(Panel_Control_5Layout);
        Panel_Control_5Layout.setHorizontalGroup(
            Panel_Control_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Control_5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Control_2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Control_5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Panel_Tools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Panel_Control_5Layout.setVerticalGroup(
            Panel_Control_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Control_5Layout.createSequentialGroup()
                .addComponent(Panel_Tools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Label_Control_2))
        );

        Button_ColorChooser2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/colorChooser.png"))); // NOI18N
        Button_ColorChooser2.setToolTipText("Color chooser");

        jLabel4.setText("Edit colors");

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(true);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton6.setContentAreaFilled(false);
        jButton6.setOpaque(true);

        Label_Control_5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_Control_5.setForeground(new java.awt.Color(90, 90, 90));
        Label_Control_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Control_5.setText("Color");

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton7.setContentAreaFilled(false);
        jButton7.setOpaque(true);

        javax.swing.GroupLayout Panel_ViewLayout = new javax.swing.GroupLayout(Panel_View);
        Panel_View.setLayout(Panel_ViewLayout);
        Panel_ViewLayout.setHorizontalGroup(
            Panel_ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_ColorChooser2)
                    .addComponent(jLabel4))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(Panel_ViewLayout.createSequentialGroup()
                .addComponent(Label_Control_5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Panel_ViewLayout.setVerticalGroup(
            Panel_ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_ViewLayout.createSequentialGroup()
                        .addComponent(Button_ColorChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(Panel_ViewLayout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(Label_Control_5))
        );

        Label_Control_4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_Control_4.setForeground(new java.awt.Color(90, 90, 90));
        Label_Control_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Control_4.setText("View");

        jLabel5.setText("Drawing Mode:");

        jRadioButton1.setText("2D");

        jRadioButton2.setText("3D");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Visual"));

        jCheckBox3.setText("Show axis");

        jCheckBox2.setText("Show coordinate");

        jCheckBox1.setText("Show grid");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox2)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox3)
                .addContainerGap())
        );

        javax.swing.GroupLayout Panel_Control_6Layout = new javax.swing.GroupLayout(Panel_Control_6);
        Panel_Control_6.setLayout(Panel_Control_6Layout);
        Panel_Control_6Layout.setHorizontalGroup(
            Panel_Control_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Control_6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_Control_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Control_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Panel_Control_6Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRadioButton1)
                            .addGap(18, 18, 18)
                            .addComponent(jRadioButton2)))
                    .addComponent(Label_Control_4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_Control_6Layout.setVerticalGroup(
            Panel_Control_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Control_6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(Panel_Control_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Control_4)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ControlArea3Layout = new javax.swing.GroupLayout(ControlArea3);
        ControlArea3.setLayout(ControlArea3Layout);
        ControlArea3Layout.setHorizontalGroup(
            ControlArea3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlArea3Layout.createSequentialGroup()
                .addComponent(Panel_Control_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Panel_Control_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Panel_Control_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Control_6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Panel_View, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        ControlArea3Layout.setVerticalGroup(
            ControlArea3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlArea3Layout.createSequentialGroup()
                .addGroup(ControlArea3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_Control_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_Control_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ControlArea3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(ControlArea3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_Control_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_View, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_Control_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ControlArea3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DrawingArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_XCoord, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_YCoord, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ControlArea3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DrawingArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_YCoord)
                            .addComponent(Label_XCoord))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void DrawingAreaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrawingAreaMouseMoved
        // TODO add your handling code here:

        Label_XCoord.setText("X: " + ((evt.getX() - (width / 2 - 1)) / (space + size)));
        Label_YCoord.setText("Y: " + (-(evt.getY() - (height / 2 + 1)) / (space + size)));
    }//GEN-LAST:event_DrawingAreaMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
            // Set windows style
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Paint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Animation1;
    private javax.swing.JButton Button_Animation2;
    private javax.swing.JButton Button_ClearAll1;
    private javax.swing.JButton Button_ColorChooser1;
    private javax.swing.JButton Button_ColorChooser2;
    private javax.swing.JButton Button_Eraser1;
    private javax.swing.JButton Button_FillColor1;
    private javax.swing.JButton Button_OpenFile;
    private javax.swing.JButton Button_OpenFile2;
    private javax.swing.JButton Button_OpenFile3;
    private javax.swing.JButton Button_Redo;
    private javax.swing.JButton Button_Redo2;
    private javax.swing.JButton Button_Redo3;
    private javax.swing.JButton Button_Save;
    private javax.swing.JButton Button_Save2;
    private javax.swing.JButton Button_Save3;
    private javax.swing.JButton Button_Select1;
    private javax.swing.JButton Button_Transform;
    private javax.swing.JButton Button_Undo;
    private javax.swing.JButton Button_Undo2;
    private javax.swing.JButton Button_Undo3;
    private javax.swing.JComboBox<String> ComboBox_LineDepth;
    private javax.swing.JComboBox<String> ComboBox_LineMode;
    private javax.swing.JPanel ControlArea;
    private javax.swing.JPanel ControlArea2;
    private javax.swing.JPanel ControlArea3;
    private javax.swing.JPanel DrawingArea;
    private javax.swing.JLabel Label_Control_1;
    private javax.swing.JLabel Label_Control_2;
    private javax.swing.JLabel Label_Control_3;
    private javax.swing.JLabel Label_Control_4;
    private javax.swing.JLabel Label_Control_5;
    private javax.swing.JLabel Label_XCoord;
    private javax.swing.JLabel Label_YCoord;
    private javax.swing.JPanel Panel_Control_1;
    private javax.swing.JPanel Panel_Control_2;
    private javax.swing.JPanel Panel_Control_3;
    private javax.swing.JPanel Panel_Control_4;
    private javax.swing.JPanel Panel_Control_5;
    private javax.swing.JPanel Panel_Control_6;
    private javax.swing.JPanel Panel_Operation;
    private javax.swing.JPanel Panel_Operation1;
    private javax.swing.JPanel Panel_Operation2;
    private javax.swing.JPanel Panel_Shapes1;
    private javax.swing.JPanel Panel_Tools;
    private javax.swing.JPanel Panel_View;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
